### ISSUE TITLE
Infografía Realidad Aumentada

### ISSUE THREAD

**Issue by JulioCesar69** [SistemasTecTlaxiaco/infografia-JulioCesar69-1#1]
![Infografía RA](https://user-images.githubusercontent.com/72415467/153694609-2cfec7ae-1db7-476f-913e-c97dc1944d12.jpg)

**Comment by claudiasilvavenda** [comment]
La infografía cumple con lo que pide la rubrica.
la calif. es 20%.

**Comment by josealfredo79** [comment]
Bien hecho y revisado
